pipeline {
    agent any
    environment {
        AWS_ACCOUNT = 'pci-account'
        S3_BUCKET = 'pcip-sdk-node.pcip.barte.com'
        AWS_CONFIG_PATH = '/tmp/aws/config'
    }
    stages {
        stage('Build') {
            agent {
                docker {
                    image 'node:20-alpine'
                }
            }
            steps {
                sh 'npm install'
                sh 'npm run build'
            }
        }
        stage('Prepare AWS CLI') {
            agent {
                docker {
                    image 'amazon/aws-cli:2.12.5'
                    args '--user root --entrypoint=""'
                }
            }
            steps {
                sh '''
                    mkdir -p /tmp/aws
                    echo "[profile ${AWS_ACCOUNT}]
region = us-east-1
role_arn = arn:aws:iam::581307502157:role/jenkins-pci
credential_source = Ec2InstanceMetadata" > ${AWS_CONFIG_PATH}
                    echo "AWS Config Created:"
                    cat ${AWS_CONFIG_PATH}
                '''
            }
        }
        stage('Validate AWS Profile') {
            agent {
                docker {
                    image 'amazon/aws-cli:2.12.5'
                    args '--user root --entrypoint="" -v /tmp/aws:/root/.aws'
                }
            }
            steps {
                sh '''
                    export AWS_CONFIG_FILE=/root/.aws/config
                    echo "Listing AWS Profiles:"
                    aws configure list-profiles
                '''
            }
        }
        stage('Clean S3 Bucket') {
            agent {
                docker {
                    image 'amazon/aws-cli:2.12.5'
                    args '--user root --entrypoint="" -v /tmp/aws:/root/.aws'
                }
            }
            steps {
                sh '''
                    export AWS_CONFIG_FILE=/root/.aws/config
                    aws s3 rm s3://${S3_BUCKET} --recursive --profile ${AWS_ACCOUNT}
                '''
            }
        }
        stage('Upload to S3') {
            agent {
                docker {
                    image 'amazon/aws-cli:2.12.5'
                    args '--user root --entrypoint="" -v /tmp/aws:/root/.aws'
                }
            }
            steps {
                sh '''
                    export AWS_CONFIG_FILE=/root/.aws/config
                    aws s3 cp dist/index.html s3://${S3_BUCKET}/ --profile ${AWS_ACCOUNT}
                    aws s3 cp dist/script.min.js s3://${S3_BUCKET}/ --profile ${AWS_ACCOUNT}
                    aws s3 cp dist/sdk.min.js s3://${S3_BUCKET}/ --profile ${AWS_ACCOUNT}
                '''
            }
        }
    }
}
